### ISSUE TITLE
Unable to run bot

### ISSUE THREAD

**Issue by ghost** [luisferreira1998/Discord-Chat-Logger#2]
Loading server.json
Finished loading server.json:
{}
Traceback (most recent call last):
  File "./src/bot.py", line 24, in <module>
    client.run(sys.argv[1])
  File "/home/ubuntu/.local/lib/python3.8/site-packages/discord/client.py", line 640, in run
    return future.result()
  File "/home/ubuntu/.local/lib/python3.8/site-packages/discord/client.py", line 621, in runner
    await self.start(*args, **kwargs)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/discord/client.py", line 585, in start
    await self.connect(reconnect=reconnect)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/discord/client.py", line 499, in connect
    await self._connect()
  File "/home/ubuntu/.local/lib/python3.8/site-packages/discord/client.py", line 463, in _connect
    await self.ws.poll_event()
  File "/home/ubuntu/.local/lib/python3.8/site-packages/discord/gateway.py", line 471, in poll_event
    await self.received_message(msg)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/discord/gateway.py", line 425, in received_message
    func(data)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/discord/state.py", line 750, in parse_guild_create
    guild = self._get_create_guild(data)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/discord/state.py", line 725, in _get_create_guild
    guild._from_data(data)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/discord/guild.py", line 297, in _from_data
    self._sync(guild)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/discord/guild.py", line 324, in _sync
    self._add_channel(TextChannel(guild=self, data=c, state=self._state))
  File "/home/ubuntu/.local/lib/python3.8/site-packages/discord/channel.py", line 107, in __init__
    self._update(guild, data)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/discord/channel.py", line 131, in _update
    self._fill_overwrites(data)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/discord/abc.py", line 294, in _fill_overwrites
    self._overwrites.append(_Overwrites(id=overridden_id, **overridden))
TypeError: __new__() got an unexpected keyword argument 'deny_new'

**Comment by jpdgoncalves** [comment]
It seems there was an update on discord API that made the version of discord.py that I was using not work anymore. It should hopefully be fixed now. Copy the new version of requirements.txt and run pip install -r requirements.txt. It should fix that error

**Comment by ghost** [comment]
Thank you it works like a charm now, how is it possible to set myself as the server owner when running commands?

**Comment by jpdgoncalves** [comment]
It seems there was another bug I never fixed. I will fix it and add a few more commands to add people that can use the bot.

**Comment by jpdgoncalves** [comment]
Fixed the bug related to not recognizing the server owner as the server owner however I don't think I will add any more commands to this bot as the changes in discord API were more significant that I thought.
